"""
Buy-side framework interrogation — PANW Q2 FY26
Follows the same stage-gate discipline as run_earnings_analysis.py.

Generates: panw_q2fy26_buyside_analysis.json

Five questions a buy-side analyst asks that reframe the sell-side output.
Each answer is generated by Claude with full earnings context loaded.
"""

import json
import os
import sqlite3
import sys
from datetime import date
from pathlib import Path

import anthropic
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent.parent.parent / ".env")

RAW  = Path(__file__).parent.parent / "raw"
DB   = Path(__file__).parent.parent / "db" / "earnings.db"
OUT  = Path(__file__).parent / "panw_q2fy26_buyside_analysis.json"
SELL = Path(__file__).parent / "panw_q2fy26_earnings_analysis.json"

def require_file(p: Path) -> Path:
    if not p.exists():
        sys.exit(f"MISSING: {p}")
    return p

def load_json(p: Path) -> dict:
    with open(require_file(p)) as f:
        return json.load(f)

def load_text(p: Path) -> str:
    with open(require_file(p)) as f:
        return f.read()

# ── Load source data ──────────────────────────────────────────────────────────
print("Loading source data...")
sell_side  = load_json(SELL)
guidance   = load_json(RAW / "panw_q2fy26_guidance.json")
transcript = load_text(RAW / "panw_q2fy26_transcript.txt")
qa_json    = load_json(RAW / "panw_q2fy26_transcript_qa.json")
crwd       = load_json(RAW / "crwd_q4fy26_results.json")
supp       = load_json(RAW / "panw_supplemental_8q.json")

conn = sqlite3.connect(DB)
conn.row_factory = sqlite3.Row
kpi_rows = conn.execute(
    "SELECT kpi_name, kpi_value FROM company_kpis WHERE symbol='PANW' AND fiscal_period='Q2_FY26'"
).fetchall()
kpis = {r["kpi_name"]: r["kpi_value"] for r in kpi_rows}
conn.close()

# ── Build context block ───────────────────────────────────────────────────────
context = f"""
=== SELL-SIDE RESEARCH NOTE (equity-research/earnings-analysis v0.1.0) ===
{json.dumps(sell_side, indent=2)}

=== KEY Q2 FY26 KPIs FROM DATABASE ===
{json.dumps(dict(kpis), indent=2)}

=== Q2 FY26 GUIDANCE ===
{json.dumps(guidance, indent=2)}

=== CRWD Q4 FY26 RESULTS (peer) ===
{json.dumps(crwd, indent=2)}

=== EARNINGS CALL Q&A EXCHANGES (tagged) ===
{json.dumps(qa_json, indent=2)}

=== TRANSCRIPT EXCERPT (management prepared remarks) ===
{transcript[:6000]}
"""

SYSTEM = """You are a senior equity analyst at a long/short technology fund with a focus on
enterprise cybersecurity. Your job is to interrogate sell-side research notes and surface
the questions that matter for portfolio decision-making — not to summarize what the sell-side
already said.

When you answer, be direct and specific. Cite numbers. Distinguish between what the data
shows and what is inference. Each answer should be 2-4 tight paragraphs. No preamble,
no "great question", no hedging filler. Lead with the most important point."""

# ── Five buy-side questions ───────────────────────────────────────────────────
QUESTIONS = [
    {
        "id": "Q1",
        "title": "Is the NGS ARR story intact?",
        "question": (
            "The sell-side headline is NGS ARR +33% YoY to $6.33B. But management called out "
            "+28% organic on the call. The 500bps gap is Chronosphere, acquired in Feb 2026. "
            "Does the organic/reported gap signal anything about underlying platform momentum, "
            "or is the 28% organic number still a clean acceleration story?"
        ),
    },
    {
        "id": "Q2",
        "title": "Q3 EPS step-down: integration tax or something else?",
        "question": (
            "Q3 EPS is guided $0.79 midpoint vs Q2 actual $1.03 — a $0.24 sequential step-down. "
            "The sell-side attributes this entirely to M&A integration costs from CyberArk and "
            "Chronosphere. Is that the complete explanation? What would a skeptic say about this "
            "guidance, and what in the call transcript supports or undermines the integration story?"
        ),
    },
    {
        "id": "Q3",
        "title": "What does CRWD's quarter say about PANW's narrative?",
        "question": (
            "CrowdStrike just reported net new ARR recovering strongly post-incident. "
            "Based on the CRWD results data provided, what is the competitive read-through "
            "for PANW's platformization thesis? Does a recovering CRWD strengthen or weaken "
            "the case for platform consolidation around PANW specifically?"
        ),
    },
    {
        "id": "Q4",
        "title": "Bull case vs. bear case on the sell-side rating",
        "question": (
            "The sell-side lands on Maintain Outperform, PT $186. Where would a conviction bull "
            "push back and say the sell-side is too conservative? Where would a bear say the "
            "sell-side is missing the real risk? Give a specific steel-man for each side — "
            "not generic risks, but the specific argument grounded in this quarter's data."
        ),
    },
    {
        "id": "Q5",
        "title": "The one number that changes everything",
        "question": (
            "If you had to pick one metric from the Q3 FY26 print — due June 2, 2026 — "
            "that would most change your view on this stock, what is it and why? "
            "Not the metric that confirms the thesis. The metric that breaks it."
        ),
    },
]

# ── Run analysis ──────────────────────────────────────────────────────────────
client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

results = []
for q in QUESTIONS:
    print(f"  Running {q['id']}: {q['title']}...")
    msg = client.messages.create(
        model="claude-opus-4-7",
        max_tokens=1024,
        system=SYSTEM,
        messages=[
            {
                "role": "user",
                "content": f"Context:\n{context}\n\n---\n\nQuestion: {q['question']}",
            }
        ],
    )
    answer = msg.content[0].text.strip()
    results.append({
        "id":       q["id"],
        "title":    q["title"],
        "question": q["question"],
        "answer":   answer,
    })
    print(f"    ✓ {len(answer)} chars")

# ── Write output ──────────────────────────────────────────────────────────────
output = {
    "generated":     str(date.today()),
    "symbol":        "PANW",
    "fiscal_period": "Q2_FY26",
    "report_date":   "2026-02-17",
    "framing":       "A sell-side analyst asks what happened. A buy-side analyst asks what it means for the thesis.",
    "questions":     results,
}

with open(OUT, "w") as f:
    json.dump(output, f, indent=2)

print(f"\n✅ {OUT}")
print(f"   {len(results)} questions answered")
